language: node_js

node_js:
  - '10'

cache:
  timeout: 10000
  directories:
    - 'node_modules'

before_install:
  - npm install -g npm && node -v && npm -v

install:
  - npm ci

script:
  - npm test
  - echo "job done"
