language: node_js

env:
  matrix:
  - NODE_VER=8
  - NODE_VER=10
cache:
  timeout: 10000
  directories:
    - 'node_modules'

before_install:
  - nvm install $NODE_VER && nvm use $NODE_VER
  - npm install -g npm jest && node -v && npm -v
install:
  - npm ci

script:
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - echo "job done"
