language: node_js
sudo: false

cache:
  timeout: 1000
  directories:
    - $HOME/.npm

env:
  matrix:
  - NODE_VER=10
  - NODE_VER=11

before_install:
  - nvm install $NODE_VER
  - npm install -g npm && node -v && npm -v

install:
  - echo `node -v`
  - echo 'npm -v'
  - npm ci

script:
  - npm test

after_success:
  - echo 'success'
